### ISSUE TITLE
Improve debug logs

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica-SCRAPERS/healthtools_ke#5]
Currently we're outputting too much logs. We should only mark successful scrapes as a whole (doctors, clinical officers, etc) instead of pages.

Other logs would be failed scrapes which should be returned as errors instead of normal print.

**Comment by andela-mabdussalam** [comment]
FIXED.

**Comment by Gathondu** [comment]
@DavidLemayian this issue should be closed? yes? no?
